[versions]
kotlin = "2.3.20"
java = "21"
springBoot = "3.5.12"
springDependencyManagement = "1.1.7"

jackson = "2.15.0"
jjwt = "0.13.0"
kotest = "6.1.7"
mockitoKotlin = "6.3.0"
kotestSpringExtension = "1.3.0"
archunit = "1.4.1"
asciidoctor = "4.0.5"
ktlint = "14.2.0"
restdocsApiSpec = "0.19.4"
springdoc = "2.8.16"

openfeignQuerydsl = "7.1"
ksp = "2.3.6"

logstashLogbackEncoder = "9.0"
loki4j = "1.6.0"
opentelemetryJdbc = "2.15.0-alpha"

redisson = "4.3.0"
jedisMock = "1.1.12"

[libraries]
# --- kotlin plugin ---
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-allopen = { module = "org.jetbrains.kotlin:kotlin-allopen", version.ref = "kotlin" }
kotlin-noarg = { module = "org.jetbrains.kotlin:kotlin-noarg", version.ref = "kotlin" }

# --- Spring Boot plugins ---
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBoot" }
spring-boot-gradle-plugin = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "springBoot" }
spring-dependency-management-plugin = { module = "io.spring.gradle:dependency-management-plugin", version.ref = "springDependencyManagement" }

# --- Spring/Core ---
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-security-core = { module = "org.springframework.security:spring-security-core" }
spring-security-test = { module = "org.springframework.security:spring-security-test" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-aop = { module = "org.springframework.boot:spring-boot-starter-aop" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-kafka = { module = "org.springframework.kafka:spring-kafka" }
spring-boot-docker-compose = { module = "org.springframework.boot:spring-boot-docker-compose" }

# --- Kotlin ---
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }

# --- Database ---
postgres = { module = "org.postgresql:postgresql", version = "42.7.10" }
h2-database = { module = "com.h2database:h2" }

# --- Redis ---
spring-boot-starter-data-redis = { module = "org.springframework.boot:spring-boot-starter-data-redis" }
redisson-spring-boot-starter = { module = "org.redisson:redisson-spring-boot-starter", version.ref = "redisson" }

# --- QueryDSL ---
openfeign-querydsl-jpa = { module = "io.github.openfeign.querydsl:querydsl-jpa", version.ref = "openfeignQuerydsl" }
openfeign-querydsl-ksp = { module = "io.github.openfeign.querydsl:querydsl-ksp-codegen", version.ref = "openfeignQuerydsl" }

# --- Security ---
jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }

# --- Testing ---
kotest-runner = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
kotest-spring = { module = "io.kotest.extensions:kotest-extensions-spring", version.ref = "kotestSpringExtension" }
archunit-junit5 = { module = "com.tngtech.archunit:archunit-junit5", version.ref = "archunit" }
restdocs-mockmvc = { module = "org.springframework.restdocs:spring-restdocs-mockmvc" }
restdocs-asciidoctor = { module = "org.springframework.restdocs:spring-restdocs-asciidoctor" }
restdocs-api-spec-mockmvc = { module = "com.epages:restdocs-api-spec-mockmvc", version.ref = "restdocsApiSpec" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
jedis-mock = { module = "com.github.fppt:jedis-mock", version.ref = "jedisMock" }
springdoc-openapi-starter-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }

# --- Tracing ---
micrometer-tracing-bridge-otel = { module = "io.micrometer:micrometer-tracing-bridge-otel" }
opentelemetry-exporter-otlp = { module = "io.opentelemetry:opentelemetry-exporter-otlp" }
opentelemetry-jdbc = { module = "io.opentelemetry.instrumentation:opentelemetry-jdbc", version.ref = "opentelemetryJdbc" }

# --- Logging ---
logstash-logback-encoder = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logstashLogbackEncoder" }

loki-logback-appender = { module = "com.github.loki4j:loki-logback-appender", version.ref = "loki4j" }

[bundles]
jjwt = ["jjwt-api", "jjwt-impl", "jjwt-jackson"]
kotest = ["kotest-runner", "kotest-assertions", "kotest-spring"]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
asciidoctor-convert = { id = "org.asciidoctor.jvm.convert", version.ref = "asciidoctor" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
restdocs-api-spec = { id = "com.epages.restdocs-api-spec", version.ref = "restdocsApiSpec" }
