spring:
  profiles:
    include: secret

logging:
  level:
    root: info
    com.playground: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5level] [%-7.7thread] [%-40.40logger{39}] - %msg%n"
