services:
  k6:
    image: grafana/k6:latest
    container_name: k6
    volumes:
      - ./scripts:/scripts
    working_dir: /scripts
    entrypoint: ["k6"]
    environment:
      - BASE_URL=http://host.docker.internal:8080
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
    command: [
      "run",
      "--out",
      "experimental-prometheus-rw",
      "--out",
      "influxdb=http://influxdb:8086/k6",
      "${SCRIPT:-order-constant-test.js}"
    ]
    networks:
      - monitoring

networks:
  monitoring:
    external: true
    name: monitoring
