management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      access: unrestricted
  metrics:
    tags:
      application: playground