management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      access: unrestricted
  metrics:
    tags:
      application: playground
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: w3c
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces  # 로컬 JVM 기동 기준. 컨테이너화 시 tempo:4318로 변경 필요