server:
  port: 8082
  shutdown: graceful

pg:
  base-url: http://localhost:9091

spring:
  application:
    name: payment-service
  lifecycle:
    timeout-per-shutdown-phase: 30s
  docker:
    compose:
      file: payment-service/docker-compose.yml
  profiles:
    include:
      - db
      - kafka
      - monitoring
