management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    tags:
      application: payment-service

logging:
  level:
    root: info
    com.playground: info
