jwt:
  secret: ${jwt.secret}
  expiration-hours: ${jwt.expiration-hours}

spring:
  profiles:
    include:
      - secret
      - monitoring
  datasource:
    url: jdbc:postgresql://localhost:5432/playground
    username: playground
    password: playground
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 20
      connection-timeout: 3000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: false

logging:
  level:
    root: info
    com.playground: info
    org.hibernate.SQL: off
    org.hibernate.orm.jdbc.bind: off
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5level] [%-7.7thread] [%-40.40logger{39}] - %msg method=%X{method}, path=%X{path}, requestId=%X{requestId}%n'

server:
  tomcat:
    threads:
      max: 200
      min-spare: 50
    accept-count: 100
    max-connections: 10000
    mbeanregistry:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: prod
logging:
  level:
    com.playground: info

---
spring:
  config:
    activate:
      on-profile: test
logging:
  level:
    com.playground: debug
