spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      observation-enabled: true
      properties:
        enable.idempotence: true
        delivery.timeout.ms: 5000
        request.timeout.ms: 3000
    consumer:
      group-id: delivery-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      observation-enabled: true
      properties:
        heartbeat.interval.ms: 1000
        session.timeout.ms: 10000
    listener:
      observation-enabled: true
