[versions]
kotlin = "2.3.10"
springBoot = "3.5.10"
springDependencyManagement = "1.1.7"
mockitoKotlin = "6.2.3"
restdocsApiSpec = "0.19.4"
ktlint = "14.0.1"

[libraries]
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
restdocs-mockmvc = { module = "org.springframework.restdocs:spring-restdocs-mockmvc" }
restdocs-api-spec-mockmvc = { module = "com.epages:restdocs-api-spec-mockmvc", version.ref = "restdocsApiSpec" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
jakarta-validation-api = { module = "jakarta.validation:jakarta.validation-api" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
restdocs-api-spec = { id = "com.epages.restdocs-api-spec", version.ref = "restdocsApiSpec" }
